---
# Example playbook
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - command: cat /etc/redhat-release
      register: multiplaybook_test_command
 
    - name: output redhat-release
      debug:
        var: multiplaybook_test_command.stdout_lines

